[[constraint]]
  branch = "renderer"
  name = "github.com/grafana/grafana_plugin_model"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  revision = "e8d22c780116115ae5624720c9af0c97afe4f551"

[[constraint]]
  name = "github.com/oracle/oci-go-sdk"
  version = "15.7.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"
